version: '3.1'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper-1
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888

  mysql-dev:
    image: mysql:5.7
    container_name: mysql-dev
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=testapp
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "3306:3306"
    #volumes:
    #  - db:/var/lib/mysql
    #  - ./docker_build/mysql/conf:/etc/mysql/conf.d
    #  - ./docker_build/mysql/init.d:/docker-entrypoint-initdb.d
  mongo:
     image: mongo:latest
     container_name: "mongodb"
     environment:
       - MONGO_DATA_DIR=/data/db
       - MONGO_LOG_DIR=/dev/null
       - MONGODB_USER="user" 
       - MONGODB_PASS="pass"
     volumes:
       - ./data/db:/data/db
     ports:
       - 27017:27017
  mongo-seed:
    image: mongo:latest
    links:
      - mongo
    volumes:
      - ./seed-data:/seed-data
    command:
      'bash -c "mongoimport --host mongodb --type json --file /seed-data/projects.json --jsonArray"'

  web:
    image: elkozmon/zoonavigator-web:0.5.0
    container_name: zoonavigator-web
    ports:
      - "8000:8000"
    environment:
      WEB_HTTP_PORT: 8000
      API_HOST: "api"
      API_PORT: 9000

    links:
      - api
    depends_on:
      - api
    restart: always
    #URL to access the zookeeper ui : http://localhost:8000
    #connection string value on the ui: zookeeper:2181
  api:
    image: elkozmon/zoonavigator-api:0.5.0
    container_name: zoonavigator-api
    environment:
      API_HTTP_PORT: 9000
    restart: always
  
